Tortoise orm support
awtkns/fastapi-crudrouter pull request #24
Opened 2021-01-17 04:30 UTC by timwford

So I run into an import error for the testclient when I try and run the tests but in theory everything works for the test implementation and I tested it by hand and it should behave the same way as the others!

2021-01-17 05:38 UTC, awtkns commented
Awesome! I will take a closer look in the morning :)

2021-01-17 05:44 UTC, awtkns requested changes

2021-01-17 05:44 UTC, awtkns commented on .idea/fastapi-crudrouter.iml
> +  <component name="TestRunnerService">
Please remove all .idea files

2021-01-17 21:58 UTC, awtkns commented on requirements.txt
> +starlette~=0.13.6
fastapi should be the only dependency

2021-01-17 21:59 UTC, awtkns commented on requirements.txt
> +starlette~=0.13.6
```suggestion
fastapi
```

2021-01-26 00:57 UTC, timwford commented
Sorry got caught up in school. I'm new to open source contributing. I see you have changes requested but I can't find them. What do I need to do? 😛

2021-01-26 01:08 UTC, awtkns commented
> Sorry got caught up in school. I'm new to open source contributing. I see you have changes requested but I can't find them. What do I need to do? 😛

I've set it all up with pytest, All that's left is to setup tortoise correctly in tests/implementations/tortoise.py so the tests pass. Currently the models never registered with tortoise. Once the tests pass we should be good to go😃

2021-02-02 01:22 UTC, awtkns requested changes
Remove db.sqlite3 files

2021-02-02 03:23 UTC, awtkns approved these changes

2021-02-02 03:57 UTC, merged

2021-02-02 03:57 UTC, awtkns commented
Awesome work @timwford . Thanks for all the help 🥇